[package]
name = "fit2csv"
version = "0.3.0"
description = "Parses .FIT files to .JSON and .CSV"
license = "Apache-2.0"
authors = ["evensolberg <even.solberg@gmail.com>"]
edition = "2021"
include = ["src/**/*", "README.md"]

[dependencies]

# Time and measurement
chrono = "0.4.19"

# System utilities
clap = "2.34.0"
csv = "1.1.6"
env_logger = "0.9.0"
# Activity-related
fitparser = "0.4.3"
log = "0.4.14"

# Serialization and export
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
uom = { version = "0.31.1", default-features = false, features = ["si", "use_serde", "u16", "f64"] }

[features]
