---
title: "Fit File Session Summaries"
author: "Even Solberg"
output: html_document
---
Report date: `r Sys.Date()`

```{r setup, include=FALSE}
# Configure Page Settings -------------------------------------------------
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE) 
knitr::opts_chunk$set(fig.align = "left")

# Load Required Packages --------------------------------------------------
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse)
pacman::p_load(ggplot2)
pacman::p_load(here)
pacman::p_load(kableExtra)
pacman::p_load(formattable)

# Helper Functions --------------------------------------------------------
not_all_na <- function(x) any(!is.na(x))
not_any_na <- function(x) all(!is.na(x))

# Read Data ---------------------------------------------------------------
# Change this to point to where ever your sessions.csv can be found.
sessions <- read_csv(here("data/sessions.csv")) %>%
    select_if(not_all_na) # Remove empty columns
```

## Activities

```{r plot_activities, message=FALSE}
#Create the graphic
sessions %>%
  group_by(activity_type)%>%
  mutate(activity_type = str_to_title(activity_type)) %>%
  summarise(n = n()) %>%
  
  ggplot(aes(x = reorder(activity_type, n), y = n, fill = activity_type)) +
    geom_bar(stat = "identity", position = "dodge") +
    geom_text(aes(label = n), position = position_dodge(width= 1), vjust= 0, hjust = -0.25, size = 3) +
    scale_y_continuous(breaks = seq(0, 1000, 10) ) +
    coord_flip() +
    theme_light() +
    theme(legend.position = "none") +
    labs(x = "Activity", y = "Count", title = "Activities Summary", fill = "Activity")

# Create the table
sessions %>%
  group_by(activity_type) %>%
  mutate(activity_type = str_to_title(activity_type)) %>%
  summarise(num_activities = n(), avg_duration = str_to_lower(lubridate::seconds_to_period(round(mean(duration_sec)))), total_duration = str_to_lower(lubridate::seconds_to_period(round(sum(duration_sec))))) %>%
  arrange(desc(num_activities)) %>%
  
  kable(col.names = c("Activity", "Number of Activities", "Average Duration", "Total Duration"),
        align = c("l", rep("r", 3)),
        caption = "Activity Overview Statistics") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"),
                font_size = 11, full_width = FALSE, position = "left")
```
